[project]
name = "flashcards"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "pypinyin>=0.51.0",
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.29.0",
]
