-- Update cards with network metadata from hsk_network_data.json
-- Total characters: 218
-- Generated: Auto-generated by seed_card_metadata.py

UPDATE cards
SET hub_score = 0.06860465116279069,
    cluster_role = 'anchor',
    semantic_domain = 'emotions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '爱';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'branch',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '八';

UPDATE cards
SET hub_score = 0.06860465116279069,
    cluster_role = 'branch',
    semantic_domain = 'family',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '爸';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '吧';

UPDATE cards
SET hub_score = 0.0313953488372093,
    cluster_role = 'anchor',
    semantic_domain = 'appearance',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '白';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'branch',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '百';

UPDATE cards
SET hub_score = 0.3732558139534883,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '班';

UPDATE cards
SET hub_score = 0.17325581395348838,
    cluster_role = 'anchor',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '半';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '帮';

UPDATE cards
SET hub_score = 0.10348837209302324,
    cluster_role = 'anchor',
    semantic_domain = 'food',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '包';

UPDATE cards
SET hub_score = 0.3616279069767442,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '杯';

UPDATE cards
SET hub_score = 0.05581395348837208,
    cluster_role = 'branch',
    semantic_domain = 'places',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '北';

UPDATE cards
SET hub_score = 0.38139534883720927,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = '木'
WHERE domain_id = 'chinese' AND question = '本';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '比';

UPDATE cards
SET hub_score = 0.12093023255813952,
    cluster_role = 'anchor',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '别';

UPDATE cards
SET hub_score = 0.043023255813953484,
    cluster_role = 'anchor',
    semantic_domain = 'body',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '病';

UPDATE cards
SET hub_score = 0.17558139534883718,
    cluster_role = 'anchor',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '不';

UPDATE cards
SET hub_score = 0.06511627906976744,
    cluster_role = 'branch',
    semantic_domain = 'food',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '菜';

UPDATE cards
SET hub_score = 0.06511627906976744,
    cluster_role = 'branch',
    semantic_domain = 'food',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '茶';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '差';

UPDATE cards
SET hub_score = 0.1127906976744186,
    cluster_role = 'anchor',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '常';

UPDATE cards
SET hub_score = 0.4511627906976744,
    cluster_role = 'branch',
    semantic_domain = 'actions',
    radical_family = '口'
WHERE domain_id = 'chinese' AND question = '唱';

UPDATE cards
SET hub_score = 0.15348837209302324,
    cluster_role = 'anchor',
    semantic_domain = 'transport',
    radical_family = '车'
WHERE domain_id = 'chinese' AND question = '车';

UPDATE cards
SET hub_score = 0.1453488372093023,
    cluster_role = 'anchor',
    semantic_domain = 'food',
    radical_family = '口'
WHERE domain_id = 'chinese' AND question = '吃';

UPDATE cards
SET hub_score = 0.40581395348837207,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '出';

UPDATE cards
SET hub_score = 0.3825581395348837,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '穿';

UPDATE cards
SET hub_score = 0.2395348837209302,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '床';

UPDATE cards
SET hub_score = 0.3732558139534883,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '次';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '从';

UPDATE cards
SET hub_score = 0.05697674418604651,
    cluster_role = 'branch',
    semantic_domain = 'emotions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '错';

UPDATE cards
SET hub_score = 0.4616279069767442,
    cluster_role = 'anchor',
    semantic_domain = 'actions',
    radical_family = '手'
WHERE domain_id = 'chinese' AND question = '打';

UPDATE cards
SET hub_score = 0.051162790697674425,
    cluster_role = 'anchor',
    semantic_domain = 'appearance',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '大';

UPDATE cards
SET hub_score = 0.44418604651162785,
    cluster_role = 'branch',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '到';

UPDATE cards
SET hub_score = 0.6651162790697674,
    cluster_role = 'anchor',
    semantic_domain = 'other',
    radical_family = '土'
WHERE domain_id = 'chinese' AND question = '地';

UPDATE cards
SET hub_score = 0.3848837209302325,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '的';

UPDATE cards
SET hub_score = 0.3825581395348837,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '等';

UPDATE cards
SET hub_score = 0.6651162790697674,
    cluster_role = 'anchor',
    semantic_domain = 'nouns',
    radical_family = '土'
WHERE domain_id = 'chinese' AND question = '地';

UPDATE cards
SET hub_score = 0.2395348837209302,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '弟';

UPDATE cards
SET hub_score = 0.3616279069767442,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '第';

UPDATE cards
SET hub_score = 0.08837209302325581,
    cluster_role = 'branch',
    semantic_domain = 'time',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '点';

UPDATE cards
SET hub_score = 0.27674418604651163,
    cluster_role = 'anchor',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '电';

UPDATE cards
SET hub_score = 0.24302325581395348,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '东';

UPDATE cards
SET hub_score = 0.38604651162790693,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '动';

UPDATE cards
SET hub_score = 0.09767441860465115,
    cluster_role = 'branch',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '都';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '读';

UPDATE cards
SET hub_score = 0.08837209302325581,
    cluster_role = 'anchor',
    semantic_domain = 'emotions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '对';

UPDATE cards
SET hub_score = 0.15,
    cluster_role = 'anchor',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '多';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '饿';

UPDATE cards
SET hub_score = 0.15,
    cluster_role = 'anchor',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '二';

UPDATE cards
SET hub_score = 0.11046511627906977,
    cluster_role = 'anchor',
    semantic_domain = 'food',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '饭';

-- Progress: 50/218 (22%)

UPDATE cards
SET hub_score = 0.39767441860465114,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '放';

UPDATE cards
SET hub_score = 0.06860465116279069,
    cluster_role = 'branch',
    semantic_domain = 'transport',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '飞';

UPDATE cards
SET hub_score = 0.06511627906976744,
    cluster_role = 'branch',
    semantic_domain = 'time',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '分';

UPDATE cards
SET hub_score = 0.22790697674418603,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '风';

UPDATE cards
SET hub_score = 0.46279069767441855,
    cluster_role = 'anchor',
    semantic_domain = 'qualities',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '干';

UPDATE cards
SET hub_score = 0.46279069767441855,
    cluster_role = 'anchor',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '干';

UPDATE cards
SET hub_score = 0.06046511627906976,
    cluster_role = 'anchor',
    semantic_domain = 'emotions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '高';

UPDATE cards
SET hub_score = 0.2395348837209302,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '哥';

UPDATE cards
SET hub_score = 0.2395348837209302,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '歌';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '个';

UPDATE cards
SET hub_score = 0.3825581395348837,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '给';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '跟';

UPDATE cards
SET hub_score = 0.43023255813953487,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = '门'
WHERE domain_id = 'chinese' AND question = '关';

UPDATE cards
SET hub_score = 0.07325581395348837,
    cluster_role = 'anchor',
    semantic_domain = 'qualities',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '贵';

UPDATE cards
SET hub_score = 0.09534883720930232,
    cluster_role = 'anchor',
    semantic_domain = 'places',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '国';

UPDATE cards
SET hub_score = 0.3825581395348837,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '过';

UPDATE cards
SET hub_score = 0.5034883720930232,
    cluster_role = 'anchor',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '还';

UPDATE cards
SET hub_score = 0.1511627906976744,
    cluster_role = 'anchor',
    semantic_domain = 'emotions',
    radical_family = '女'
WHERE domain_id = 'chinese' AND question = '好';

UPDATE cards
SET hub_score = 0.4069767441860465,
    cluster_role = 'branch',
    semantic_domain = 'other',
    radical_family = '口'
WHERE domain_id = 'chinese' AND question = '号';

UPDATE cards
SET hub_score = 0.12209302325581395,
    cluster_role = 'anchor',
    semantic_domain = 'food',
    radical_family = '口'
WHERE domain_id = 'chinese' AND question = '喝';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '和';

UPDATE cards
SET hub_score = 0.09767441860465115,
    cluster_role = 'branch',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '很';

UPDATE cards
SET hub_score = 0.25465116279069766,
    cluster_role = 'branch',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '后';

UPDATE cards
SET hub_score = 0.22790697674418603,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '花';

UPDATE cards
SET hub_score = 0.2709302325581395,
    cluster_role = 'anchor',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '话';

UPDATE cards
SET hub_score = 0.05697674418604651,
    cluster_role = 'branch',
    semantic_domain = 'emotions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '坏';

UPDATE cards
SET hub_score = 0.5034883720930232,
    cluster_role = 'anchor',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '还';

UPDATE cards
SET hub_score = 0.11511627906976743,
    cluster_role = 'anchor',
    semantic_domain = 'transport',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '回';

UPDATE cards
SET hub_score = 0.40581395348837207,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '会';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'branch',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '几';

UPDATE cards
SET hub_score = 0.4093023255813953,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '记';

UPDATE cards
SET hub_score = 0.10697674418604651,
    cluster_role = 'anchor',
    semantic_domain = 'places',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '家';

UPDATE cards
SET hub_score = 0.4127906976744186,
    cluster_role = 'anchor',
    semantic_domain = 'other',
    radical_family = '门'
WHERE domain_id = 'chinese' AND question = '间';

UPDATE cards
SET hub_score = 0.42093023255813955,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '见';

UPDATE cards
SET hub_score = 0.4023255813953488,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '教';

UPDATE cards
SET hub_score = 0.4395348837209302,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = '口'
WHERE domain_id = 'chinese' AND question = '叫';

UPDATE cards
SET hub_score = 0.2837209302325581,
    cluster_role = 'anchor',
    semantic_domain = 'nouns',
    radical_family = '女'
WHERE domain_id = 'chinese' AND question = '姐';

UPDATE cards
SET hub_score = 0.4174418604651163,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '进';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'branch',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '九';

UPDATE cards
SET hub_score = 0.09767441860465115,
    cluster_role = 'leaf',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '就';

UPDATE cards
SET hub_score = 0.45348837209302323,
    cluster_role = 'branch',
    semantic_domain = 'actions',
    radical_family = '门'
WHERE domain_id = 'chinese' AND question = '开';

UPDATE cards
SET hub_score = 0.42906976744186043,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '看';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '考';

UPDATE cards
SET hub_score = 0.07325581395348837,
    cluster_role = 'branch',
    semantic_domain = 'qualities',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '渴';

UPDATE cards
SET hub_score = 0.26627906976744187,
    cluster_role = 'branch',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '课';

UPDATE cards
SET hub_score = 0.09651162790697673,
    cluster_role = 'anchor',
    semantic_domain = 'body',
    radical_family = '口'
WHERE domain_id = 'chinese' AND question = '口';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'branch',
    semantic_domain = 'other',
    radical_family = '土'
WHERE domain_id = 'chinese' AND question = '块';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '快';

UPDATE cards
SET hub_score = 0.1430232558139535,
    cluster_role = 'anchor',
    semantic_domain = 'transport',
    radical_family = '木'
WHERE domain_id = 'chinese' AND question = '来';

UPDATE cards
SET hub_score = 0.07209302325581395,
    cluster_role = 'branch',
    semantic_domain = 'family',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '老';

-- Progress: 100/218 (45%)

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '了';

UPDATE cards
SET hub_score = 0.05697674418604651,
    cluster_role = 'branch',
    semantic_domain = 'emotions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '累';

UPDATE cards
SET hub_score = 0.07325581395348837,
    cluster_role = 'branch',
    semantic_domain = 'qualities',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '冷';

UPDATE cards
SET hub_score = 0.1627906976744186,
    cluster_role = 'anchor',
    semantic_domain = 'places',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '里';

UPDATE cards
SET hub_score = 0.1627906976744186,
    cluster_role = 'anchor',
    semantic_domain = 'places',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '里';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'branch',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '两';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'leaf',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '零';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'leaf',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '〇';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'leaf',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '六';

UPDATE cards
SET hub_score = 0.2709302325581395,
    cluster_role = 'anchor',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '楼';

UPDATE cards
SET hub_score = 0.3883720930232558,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '路';

UPDATE cards
SET hub_score = 0.1011627906976744,
    cluster_role = 'anchor',
    semantic_domain = 'family',
    radical_family = '女'
WHERE domain_id = 'chinese' AND question = '妈';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '吗';

UPDATE cards
SET hub_score = 0.3825581395348837,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '买';

UPDATE cards
SET hub_score = 0.07325581395348837,
    cluster_role = 'branch',
    semantic_domain = 'qualities',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '慢';

UPDATE cards
SET hub_score = 0.07674418604651162,
    cluster_role = 'anchor',
    semantic_domain = 'emotions',
    radical_family = '心'
WHERE domain_id = 'chinese' AND question = '忙';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '毛';

UPDATE cards
SET hub_score = 0.4046511627906976,
    cluster_role = 'branch',
    semantic_domain = 'other',
    radical_family = '水'
WHERE domain_id = 'chinese' AND question = '没';

UPDATE cards
SET hub_score = 0.2395348837209302,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '妹';

UPDATE cards
SET hub_score = 0.3732558139534883,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '门';

UPDATE cards
SET hub_score = 0.43255813953488365,
    cluster_role = 'anchor',
    semantic_domain = 'other',
    radical_family = '人'
WHERE domain_id = 'chinese' AND question = '们';

UPDATE cards
SET hub_score = 0.4069767441860465,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = '手'
WHERE domain_id = 'chinese' AND question = '拿';

UPDATE cards
SET hub_score = 0.3802325581395348,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '哪';

UPDATE cards
SET hub_score = 0.38372093023255816,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '那';

UPDATE cards
SET hub_score = 0.24302325581395348,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '奶';

UPDATE cards
SET hub_score = 0.07906976744186046,
    cluster_role = 'branch',
    semantic_domain = 'family',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '男';

UPDATE cards
SET hub_score = 0.23139534883720927,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '南';

UPDATE cards
SET hub_score = 0.07325581395348837,
    cluster_role = 'branch',
    semantic_domain = 'qualities',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '难';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '呢';

UPDATE cards
SET hub_score = 0.3825581395348837,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '能';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'branch',
    semantic_domain = 'other',
    radical_family = '人'
WHERE domain_id = 'chinese' AND question = '你';

UPDATE cards
SET hub_score = 0.10697674418604651,
    cluster_role = 'anchor',
    semantic_domain = 'time',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '年';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '您';

UPDATE cards
SET hub_score = 0.11511627906976743,
    cluster_role = 'anchor',
    semantic_domain = 'family',
    radical_family = '女'
WHERE domain_id = 'chinese' AND question = '女';

UPDATE cards
SET hub_score = 0.06511627906976744,
    cluster_role = 'branch',
    semantic_domain = 'transport',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '跑';

UPDATE cards
SET hub_score = 0.09186046511627907,
    cluster_role = 'anchor',
    semantic_domain = 'transport',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '票';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'leaf',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '七';

UPDATE cards
SET hub_score = 0.4569767441860465,
    cluster_role = 'branch',
    semantic_domain = 'actions',
    radical_family = '走'
WHERE domain_id = 'chinese' AND question = '起';

UPDATE cards
SET hub_score = 0.2593023255813954,
    cluster_role = 'branch',
    semantic_domain = 'nouns',
    radical_family = '月'
WHERE domain_id = 'chinese' AND question = '前';

UPDATE cards
SET hub_score = 0.2395348837209302,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '钱';

UPDATE cards
SET hub_score = 0.42093023255813955,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '请';

UPDATE cards
SET hub_score = 0.2395348837209302,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '球';

UPDATE cards
SET hub_score = 0.11162790697674416,
    cluster_role = 'anchor',
    semantic_domain = 'transport',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '去';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '热';

UPDATE cards
SET hub_score = 0.1627906976744186,
    cluster_role = 'anchor',
    semantic_domain = 'family',
    radical_family = '人'
WHERE domain_id = 'chinese' AND question = '人';

UPDATE cards
SET hub_score = 0.09186046511627907,
    cluster_role = 'branch',
    semantic_domain = 'time',
    radical_family = '日'
WHERE domain_id = 'chinese' AND question = '日';

UPDATE cards
SET hub_score = 0.06511627906976744,
    cluster_role = 'branch',
    semantic_domain = 'food',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '肉';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'leaf',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '三';

UPDATE cards
SET hub_score = 0.22790697674418603,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '山';

UPDATE cards
SET hub_score = 0.2255813953488372,
    cluster_role = 'anchor',
    semantic_domain = 'time',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '上';

-- Progress: 150/218 (68%)

UPDATE cards
SET hub_score = 0.15,
    cluster_role = 'anchor',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '少';

UPDATE cards
SET hub_score = 0.691860465116279,
    cluster_role = 'anchor',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '谁';

UPDATE cards
SET hub_score = 0.691860465116279,
    cluster_role = 'anchor',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '谁';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'leaf',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '十';

UPDATE cards
SET hub_score = 0.2395348837209302,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '事';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '试';

UPDATE cards
SET hub_score = 0.42209302325581394,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '是';

UPDATE cards
SET hub_score = 0.06395348837209301,
    cluster_role = 'anchor',
    semantic_domain = 'body',
    radical_family = '手'
WHERE domain_id = 'chinese' AND question = '手';

UPDATE cards
SET hub_score = 0.25813953488372093,
    cluster_role = 'branch',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '书';

UPDATE cards
SET hub_score = 0.22790697674418603,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '树';

UPDATE cards
SET hub_score = 0.08488372093023255,
    cluster_role = 'branch',
    semantic_domain = 'food',
    radical_family = '水'
WHERE domain_id = 'chinese' AND question = '水';

UPDATE cards
SET hub_score = 0.38604651162790693,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '睡';

UPDATE cards
SET hub_score = 0.4511627906976744,
    cluster_role = 'branch',
    semantic_domain = 'actions',
    radical_family = '口'
WHERE domain_id = 'chinese' AND question = '说';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'leaf',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '四';

UPDATE cards
SET hub_score = 0.3825581395348837,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '送';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '岁';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'branch',
    semantic_domain = 'other',
    radical_family = '人'
WHERE domain_id = 'chinese' AND question = '他';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = '女'
WHERE domain_id = 'chinese' AND question = '她';

UPDATE cards
SET hub_score = 0.09767441860465115,
    cluster_role = 'leaf',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '太';

UPDATE cards
SET hub_score = 0.12906976744186044,
    cluster_role = 'anchor',
    semantic_domain = 'time',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '天';

UPDATE cards
SET hub_score = 0.48604651162790696,
    cluster_role = 'anchor',
    semantic_domain = 'actions',
    radical_family = '口'
WHERE domain_id = 'chinese' AND question = '听';

UPDATE cards
SET hub_score = 0.07906976744186046,
    cluster_role = 'branch',
    semantic_domain = 'places',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '外';

UPDATE cards
SET hub_score = 0.1127906976744186,
    cluster_role = 'anchor',
    semantic_domain = 'qualities',
    radical_family = '日'
WHERE domain_id = 'chinese' AND question = '晚';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '忘';

UPDATE cards
SET hub_score = 0.4186046511627906,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = '门'
WHERE domain_id = 'chinese' AND question = '问';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = '人'
WHERE domain_id = 'chinese' AND question = '我';

UPDATE cards
SET hub_score = 0.1383720930232558,
    cluster_role = 'leaf',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '五';

UPDATE cards
SET hub_score = 0.24302325581395348,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '西';

UPDATE cards
SET hub_score = 0.4186046511627906,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = '水'
WHERE domain_id = 'chinese' AND question = '洗';

UPDATE cards
SET hub_score = 0.16511627906976745,
    cluster_role = 'anchor',
    semantic_domain = 'time',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '下';

UPDATE cards
SET hub_score = 0.1011627906976744,
    cluster_role = 'branch',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '先';

UPDATE cards
SET hub_score = 0.3906976744186046,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = '心'
WHERE domain_id = 'chinese' AND question = '想';

UPDATE cards
SET hub_score = 0.10232558139534885,
    cluster_role = 'anchor',
    semantic_domain = 'family',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '小';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '笑';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '写';

UPDATE cards
SET hub_score = 0.02790697674418604,
    cluster_role = 'anchor',
    semantic_domain = 'appearance',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '新';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '行';

UPDATE cards
SET hub_score = 0.20348837209302326,
    cluster_role = 'anchor',
    semantic_domain = 'family',
    radical_family = '子'
WHERE domain_id = 'chinese' AND question = '学';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '要';

UPDATE cards
SET hub_score = 0.09767441860465115,
    cluster_role = 'leaf',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '也';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '页';

UPDATE cards
SET hub_score = 0.23023255813953486,
    cluster_role = 'anchor',
    semantic_domain = 'numbers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '一';

UPDATE cards
SET hub_score = 0.40581395348837207,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '用';

UPDATE cards
SET hub_score = 0.47093023255813954,
    cluster_role = 'anchor',
    semantic_domain = 'actions',
    radical_family = '月'
WHERE domain_id = 'chinese' AND question = '有';

UPDATE cards
SET hub_score = 0.23139534883720927,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '右';

UPDATE cards
SET hub_score = 0.2395348837209302,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '雨';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '元';

UPDATE cards
SET hub_score = 0.07325581395348837,
    cluster_role = 'branch',
    semantic_domain = 'qualities',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '远';

UPDATE cards
SET hub_score = 0.08139534883720931,
    cluster_role = 'branch',
    semantic_domain = 'time',
    radical_family = '月'
WHERE domain_id = 'chinese' AND question = '月';

UPDATE cards
SET hub_score = 0.10930232558139535,
    cluster_role = 'branch',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '再';

-- Progress: 200/218 (91%)

UPDATE cards
SET hub_score = 0.12441860465116278,
    cluster_role = 'anchor',
    semantic_domain = 'time',
    radical_family = '土'
WHERE domain_id = 'chinese' AND question = '在';

UPDATE cards
SET hub_score = 0.1127906976744186,
    cluster_role = 'anchor',
    semantic_domain = 'qualities',
    radical_family = '日'
WHERE domain_id = 'chinese' AND question = '早';

UPDATE cards
SET hub_score = 0.07674418604651162,
    cluster_role = 'branch',
    semantic_domain = 'transport',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '站';

UPDATE cards
SET hub_score = 0.4186046511627906,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = '手'
WHERE domain_id = 'chinese' AND question = '找';

UPDATE cards
SET hub_score = 0.3720930232558139,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '这';

UPDATE cards
SET hub_score = 0.35,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '着';

UPDATE cards
SET hub_score = 0.3651162790697674,
    cluster_role = 'leaf',
    semantic_domain = 'other',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '真';

UPDATE cards
SET hub_score = 0.10930232558139535,
    cluster_role = 'branch',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '正';

UPDATE cards
SET hub_score = 0.10232558139534885,
    cluster_role = 'anchor',
    semantic_domain = 'places',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '中';

UPDATE cards
SET hub_score = 0.08488372093023255,
    cluster_role = 'anchor',
    semantic_domain = 'qualities',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '重';

UPDATE cards
SET hub_score = 0.3941860465116278,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '住';

UPDATE cards
SET hub_score = 0.25116279069767444,
    cluster_role = 'branch',
    semantic_domain = 'nouns',
    radical_family = '子'
WHERE domain_id = 'chinese' AND question = '字';

UPDATE cards
SET hub_score = 0.13372093023255813,
    cluster_role = 'anchor',
    semantic_domain = 'food',
    radical_family = '子'
WHERE domain_id = 'chinese' AND question = '子';

UPDATE cards
SET hub_score = 0.08488372093023255,
    cluster_role = 'branch',
    semantic_domain = 'transport',
    radical_family = '走'
WHERE domain_id = 'chinese' AND question = '走';

UPDATE cards
SET hub_score = 0.12093023255813952,
    cluster_role = 'anchor',
    semantic_domain = 'modifiers',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '最';

UPDATE cards
SET hub_score = 0.23139534883720927,
    cluster_role = 'leaf',
    semantic_domain = 'nouns',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '左';

UPDATE cards
SET hub_score = 0.43837209302325575,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = '土'
WHERE domain_id = 'chinese' AND question = '坐';

UPDATE cards
SET hub_score = 0.3825581395348837,
    cluster_role = 'leaf',
    semantic_domain = 'actions',
    radical_family = NULL
WHERE domain_id = 'chinese' AND question = '做';

-- Update complete
-- Statistics:
--   Total updated: 218
--   Anchors: 66
--   Branches: 50
--   Leaves: 102
